version: "3"

####################################
# application network
####################################
networks:
  laravel:


####################################
# services
####################################
services:
  
  ####################################
  # service 1
  ####################################
  some-service:
    # source
    image: nginx
    build:
      context: ./configs/php
      dockerfile: Dockerfile
    # name
    container_name: php
    # volumes
    volumes:
      - ./code/backend:/var/www/html
      - ./code:/var/www/html2
    # ports
    ports:
      - "9000:9000"
      - "8000:80"
    # network
    networks:
      - laravel
    # depends on
    depends_on:
      - php
    # more
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  ####################################
  # service 2
  ####################################
  mysql:
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql